### ISSUE TITLE
Execution Error

### ISSUE THREAD

**Issue by AasiaRehman** [Confusezius/LiTS_2D_Segmentation_Pipeline#10]
May I know what is this error about

 0% 0/4165 [00:00<?, ?it/s]
 train_iter 4165
  0% 0/4165 [00:00<?, ?it/s]
(#26453082) Training [lr=[3.e-05]]:   0% 0/50 [00:00<?, ?it/s]
Setup Iteration... :   0% 0/1 [00:05<?, ?it/s]
Traceback (most recent call last):
  File "/content/drive/MyDrive/My Drive/Tversky Loss/Train_Networks/Train_Networks.py", line 235, in <module>
    main(training_setup)
  File "/content/drive/MyDrive/My Drive/Tversky Loss/Train_Networks/Train_Networks.py", line 137, in main
    flib.trainer([network,optimizer], train_data_loader, [base_loss_func, aux_loss_func], opt, Metrics, epoch)
  File "/content/drive/MyDrive/My Drive/Tversky Loss/Train_Networks/Function_Library.py", line 36, in trainer
    for slice_idx, file_dict in enumerate(train_data_iter):
  File "/usr/local/lib/python3.7/dist-packages/tqdm/std.py", line 1180, in __iter__
    for obj in iterable:
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py", line 1203, in _next_data
    return self._process_data(data)
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py", line 1229, in _process_data
    data.reraise()
  File "/usr/local/lib/python3.7/dist-packages/torch/_utils.py", line 434, in reraise
    raise exception
ValueError: Caught ValueError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/content/drive/MyDrive/My Drive/Tversky Loss/Utilities/PyTorch_Datasets.py", line 161, in __getitem__
    crops_for_picked_batch  = gu.get_crops_per_batch(files_to_crop, crop_mask, crop_size=self.pars.Training['crop_size'], seed=self.rng.randint(0,1e8))
  File "/content/drive/MyDrive/My Drive/Tversky Loss/Utilities/General_Utilities.py", line 307, in get_crops_per_batch
    crop_idx = [rng.randint(crop_size[i]//2-1,np.array(batch_to_crop[0].shape[i+1])-crop_size[i]//2-1) for i in range(batch_to_crop[0].ndim-1)]
  File "/content/drive/MyDrive/My Drive/Tversky Loss/Utilities/General_Utilities.py", line 307, in <listcomp>
    crop_idx = [rng.randint(crop_size[i]//2-1,np.array(batch_to_crop[0].shape[i+1])-crop_size[i]//2-1) for i in range(batch_to_crop[0].ndim-1)]
  File "mtrand.pyx", line 746, in numpy.random.mtrand.RandomState.randint
  File "_bounded_integers.pyx", line 1254, in numpy.random._bounded_integers._rand_int64
ValueError: low >= high

**Comment by U-C-J** [comment]
It happens in cropping. 

e.g. randint(127,127) gives you this error because the high value should be larger than 127. 

Adjust the input size and the crop size to avoid this error.
